### ISSUE TITLE
Should the  Interlocked class be used?

### ISSUE THREAD

**Issue by coderdnewbie** [Darkseal/LockProvider#2]
I was learning more about threads last week, and found out that the Interlocked class is the thread safe way for increment and decrement.

So instead of _waiters++; it should be 

Interlocked.Increment(ref _waiters);

and instead of _waiters—; it should be

Interlocked.Decrement(ref _waiters);

Have you had any problems with the _waiters variable in your tests?

**Comment by Darkseal** [comment]
Not yet, but your suggestion seems reasonable enough: I can patch the code accordingly, it seems like a solid suggestion.
