### ISSUE TITLE
Found a different way

### ISSUE THREAD

**Issue by coderdnewbie** [Darkseal/LockProvider#5]
Found this in a Microsoft repo

https://github.com/microsoft/FASTER/blob/master/cs/src/core/Utilities/SafeConcurrentDictionary.cs

This is a simpler solution to the atomicity problem but not sure if it needs the lazy wrapped on it, just wanted to share.

**Comment by Darkseal** [comment]
Hi @coderdnewbie, 

many thanks for your contribution!

MS solutions looks good enough, however I don't think that implementing the `SafeConcurrentDictionary` will simplify this library: `SafeConcurrentDictionary` is not in the framework (yet), therefore I would have to either re-implement it or copy/paste the MS code as a separate class, which doesn't seem that great.

Anyway, I'll wait for #4 to close so I can see the best way to update the code to solve the atomicity issue using less code as possible.
